env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2022
  sourceType: module
plugins:
  - '@typescript-eslint'
  - jest
ignorePatterns:
  - webpack.*.js
rules:
  jest/no-standalone-expect: off
  '@typescript-eslint/ban-ts-comment': off
  semi:
    - error
    - never
    - beforeStatementContinuationChars: never
  semi-spacing:
    - error
    - after: true
      before: false
  semi-style:
    - error
    - first
  no-extra-semi: error
  no-unexpected-multiline: error
  no-unreachable: error
  no-tabs: error
  no-trailing-spaces:
    - error
    - ignoreComments: true
      skipBlankLines: true
  no-unneeded-ternary: error
  no-whitespace-before-property: error
  no-var: error
  no-console:
    - error
    - allow:
        - error
        - trace
  indent:
    - error
    - 4
    - SwitchCase: 1
      MemberExpression: off
      FunctionDeclaration:
        parameters: off
      FunctionExpression:
        parameters: off
      ObjectExpression: first
      ignoreComments: true
  comma-spacing: error
  prefer-template: warn
  arrow-parens:
    - warn
    - as-needed
  require-await: warn
